Start game func
lesssnic/DE_CP_GuessNumber pull request #10
Opened 2021-11-06 15:07 UTC by richerstars

2021-11-06 16:50 UTC, lesssnic commented on src/app.js
> +    if (Number(min.value) >= Number(max.value) || (min.value < 0 || max.value < 0) || (min.value > 200 || max.value > 200)) {
У нас есть фнкция валидатор, вот тут можно ей пользоваться, красивее будет

2021-11-06 16:52 UTC, lesssnic commented on index.html
> +        <button id="exit" class="buttons_list" onclick="window.location.reload()">Сброс</button>
на мой взгляд плохая идея страницу перезагружать, лучше отдельно переменные обнулить

2021-11-06 16:56 UTC, lesssnic commented on src/app.js
>          return outputtterError.innerHTML = 'Ваш диапазон задан неверно!';
outputtter   -- так задумывалось?)))))

2021-11-06 16:59 UTC, lesssnic commented on index.html
>      <script src="./src/app.js"></script>
Это дубль, вверху уже скрипт подключен, параметр defer говорит о том, что он запустится только просто прогрузки html

2021-11-06 17:04 UTC, lesssnic commented on src/app.js
> +        const random = getRandomNumber(Number(min.value), Number(max.value));
здесь random лишняя переменная, ты ее уже снаружи определил как randRes

2021-11-06 17:07 UTC, lesssnic commented on src/app.js
> +            case user.value < randRes:
тут user.value лучше достать один раз после if  перед switch в переменную и к Number сразу привести

2021-11-06 17:11 UTC, lesssnic requested changes
в целом хорошо, только переделать по комментам

2021-11-11 13:32 UTC, richerstars commented on src/app.js
> +            case user.value < randRes:
+

2021-11-11 13:32 UTC, richerstars commented on src/app.js
> +        const random = getRandomNumber(Number(min.value), Number(max.value));
+

2021-11-11 13:33 UTC, richerstars commented on index.html
>      <script src="./src/app.js"></script>
+

2021-11-11 13:33 UTC, richerstars commented on src/app.js
>          return outputtterError.innerHTML = 'Ваш диапазон задан неверно!';
+

2021-11-11 13:33 UTC, richerstars commented on index.html
> +        <button id="exit" class="buttons_list" onclick="window.location.reload()">Сброс</button>
+

2021-11-11 14:04 UTC, richerstars commented on src/app.js
> +    if (Number(min.value) >= Number(max.value) || (min.value < 0 || max.value < 0) || (min.value > 200 || max.value > 200)) {
+

2021-11-11 15:47 UTC, closed without merging